---
apiVersion: v1
kind: Namespace
metadata:
  name: rideshare-dev
  labels:
    environment: dev
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: rideshare-staging
  labels:
    environment: staging
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: rideshare-prod
  labels:
    environment: prod
    managed-by: argocd
